package com.example.collateralmanagement.domain.entities.enums;

public enum CollateralCategory {
    DEPOSIT,
    FINANCIAL_ASSET,
    BUSINESS_ENTITY,
    APARTMENT,
    HOUSE,
    GARAGE,
    RESIDENTIAL_BUILDING,
    OFFICE,
    OFFICE_BUILDING,
    COMMERCIAL_PREMISE,
    COMMERCIAL_BUILDING,
    INDUSTRIAL_PROPERTY,
    GAS_STATION,
    AGRICULTURE_PREMISE,
    AGRICULTURE_LAND,
    LAND_FOR_CONSTRUCTION,
    LAND_FOR_OTHER_PURPOSES,
    TRANSPORTATION_VEHICLES,
    AGRICULTURE_EQUIPMENT,
    PRODUCTION_MACHINERY_AND_EQUIPMENT,
    OTHER_MACHINERY_AND_EQUIPMENT

}
