package com.example.collateralmanagement.models.enums;

public enum CollateralCategory {

    APARTMENT,
    HOUSE,
    GARAGE,
    RESIDENTIAL_BUILDING,
    OFFICE,
    ADMINISTRATIVE_BUILDING,
    STORE,
    RESTAURANT,
    COMMERCIAL_BUILDING,
    HOTEL,
    PRODUCTION_AND_STORAGE_PREMISE_IN_RESIDENTIAL_AREAS,
    PRODUCTION_AND_STORAGE_PREMISE_OUTSIDE_RESIDENTIAL_AREAS,
    GAS_STATION,
    OTHER_INDUSTRIAL_PROPERTY,
    AGRICULTURE_PREMISE,
    AGRICULTURE_LAND,
    LAND_FOR_CONSTRUCTION,
    LAND_FOR_OTHER_PURPOSES,
    TRANSPORTATION_VEHICLES,
    AGRICULTURE_EQUIPMENT,
    PRODUCTION_MACHINERY_AND_EQUIPMENT,
    OTHER_MACHINERY_AND_EQUIPMENT,
    INVENTORY,
    RECEIVABLE,
    LIVESTOCK,
    DEPOSIT,
    FINANCIAL_ASSET,
    BUSINESS_ENTITY,
    OTHERS
}
